import type { Metadata } from "next";
import { Electrolize } from "next/font/google";
import "./globals.scss";

const electrolize = Electrolize({
    weight: ["400"],
    subsets: ["latin"],
    variable: "--font-electrolize",
});

export const metadata: Metadata = {
    title: "Profile",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${electrolize.variable}`}>{children}</body>
        </html>
    );
}
